version: "2"

linters:
  default: none
  enable:
    - govet
    - gocyclo
    - gocritic
    - ineffassign
    - misspell
    - unused
    - goconst
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
  exclusions:
    rules:
      - path: "_test\\.go"
        linters: [gocyclo, govet, gocritic]
      - path: "_test\\.go"
        linters: [goconst]

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hugofrely/envswitch

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: true
      print-issued-lines: true

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
